Repository NotOnlyStudents/Documentazione, pull requests merged in 2021-03, with the labels that each got.

#193 Feature/uc venditore
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Estensioni.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneAccountVenditore.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneCategorie.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneOrdini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneProdotto.tex
Labels: UC Venditore, Use Case, adr, documentation, enhancement, help wanted, question, verifica, wontfix

#206 Feature/uc venditore 01 03
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneAccountVenditore.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneCategorie.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneOrdini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneProdotto.tex
Labels: UC Venditore, Use Case, adr, documentation, verifica

#207 Sistemata gestione informazioni acquirente
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/Checkout.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/GestioneCarta.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/GestioneIndirizzo.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/GestioneAccountAcquirente.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Attori.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Estensioni.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneAccountVenditore.tex
Labels: UC Acquirente, Use Case, adr, documentation

#209 Update Estensioni.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Estensioni.tex
Labels: Use Case, adr, documentation, verifica

#211 Feature/sistemare accesso alla piattaforma
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/AccessoAllaPiattaforma.tex
Labels: UC Utente non autenticato, Use Case, adr, documentation

#210 Redazione verbale 02/03
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/M.tex
  DocumentiPubblici/Glossario/Sezioni/Comandi.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_02_06/Sezioni/Contenuto.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_02/Sezioni/Comandi.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_02/Sezioni/Contenuto.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_02/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_02/VE_2021_03_02.tex
  Utilita/Stiletemplate.sty
Labels: documentation, verbale, verifica

#212 Feature/correzioni generali 03 03
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Attori.png
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/AccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Carrello.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/Checkout.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/GestioneIndirizzo.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/GestioneAccountAcquirente.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Ordini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/PDP.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/PLP.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/RicercaDeiProdotti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Attori.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Estensioni.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneAccountVenditore.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneCategorie.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneOrdini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneProdotto.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/DescrizioneDelProdotto.tex
Labels: UC Acquirente, UC Utente non autenticato, UC Venditore, adr, documentation, verifica

#215 Feature/aggiunta custom label
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/AccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Carrello.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/Checkout.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/GestioneIndirizzo.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/GestioneAccountAcquirente.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Ordini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/PDP.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/PLP.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/RicercaDeiProdotti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Attori.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Estensioni.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/InserimentoCampoDati.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneAccountVenditore.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneCategorie.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneOrdini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneProdotto.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Comandi.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisiAccessoAllaPiattaforma.tex
  Utilita/Stiletemplate.sty
Labels: Use Case, adr, documentation

#216 Feature/requisiti acquirente
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/AccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Carrello.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/Checkout.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/GestioneAccountAcquirente.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Ordini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Comandi.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisiAccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiCarrello.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiCheckout.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiGestioneAccountAcquirente.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiHome.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiOrdini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiPDP.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiPLP.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiRicercaDeiProdotti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Prestazionali.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Qualita.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Vincoli.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Tracciamento/FonteRequisiti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Tracciamento/RequisitoFonti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Tracciamento/Riepilogo.tex
Labels: adr, documentation, requisiti

#222 Modificato requisiti venditore
  DocumentiPubblici/AnalisiDeiRequisiti/AnalisiDeiRequisiti_v1.14.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneOrdini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneProdotto.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiCarrello.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiCheckout.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiVenditore/RequisitiCategoria.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiVenditore/RequisitiGestioneAccountVenditore.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiVenditore/RequisitiGestioneOrdini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiVenditore/RequisitiProdotto.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiVenditore/RequisitiRicercaDeiProdottiVenditore.tex
Labels: adr, documentation, requisiti

#226 Aggiunti gli uml del venditore
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAcquirente.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/OrdinamentoProdotti.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC1.1Registrazione.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC1.2Login.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC1.3PasswordDimenticata.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC10VisualizzazioneProdottiNelCarrello.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC11AggiuntaProdottoAlCarrello.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC13Checkout.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC15.1InserimentoNuovaPassword.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC15ModificaInformazioniProfilo.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC18AggiuntaProdotto.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC19ModificaProdotto.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC1AccessoAllaPiattaforma.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC20EliminazioneProdotto.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC3.1MenuUtenteNonAutenticato.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC3.2MenuAcquirente.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC3.2MenuUtenteAutenticato.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC3AccessoAlMenu.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC5RicercaDeiProdotti.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC6FiltraggioProdottiDellaPLP.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UC7Ordinamento.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Venditore/AggiuntaCategoria.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Venditore/AggiuntaProdotto.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Venditore/FiltraggioOrdiniVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Venditore/FiltraggioProdottiPLPVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Venditore/FiltroIntervalloTemporaleVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Venditore/ModificaCategoria.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Venditore/ModificaInformazioniVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Venditore/ModificaPasswordVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Venditore/ModificaProdotto.png
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/AccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Carrello.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/Checkout.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/RicercaDeiProdotti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneAccountVenditore.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneCategorie.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneOrdini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneProdotto.tex
Labels: UC Venditore, Use Case, adr, documentation

#225 Feature/uml acquirente
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/AggiuntaProdottiCarrelloPDP.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/AggiuntaProdottiCarrelloPLP.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/AutenticazioneAcquirente.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/AutenticazioneVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/Checkout.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/FiltraggioProdotti.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/FiltroTemporaleAcquirente.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/InserimentoDatiAutenticazione.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/InserimentoDatiIndirizzoConsegna.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/InserimentoDatiRegistrazione.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/InserimentoIndirizzoConsegna.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/ModificaIndirizzoConsegna.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/ModificaInformazioniAcquirente.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/ModificaPasswordAcquirente.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/PasswordDimenticata.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/Registrazione.png
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/AccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Carrello.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/Checkout.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/GestioneIndirizzo.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/GestioneAccountAcquirente.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Ordini.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/PDP.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/PLP.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/RicercaDeiProdotti.tex
Labels: UC Acquirente, UC Utente non autenticato, Use Case, adr, documentation

#229 Feature/fonte requisito
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Comandi.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiGestioneAccountAcquirente.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiRicercaDeiProdotti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Tracciamento/FonteRequisiti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Tracciamento/RequisitoFonti.tex
Labels: adr, documentation, requisiti

#230 Feature/update metriche/28 02
  DocumentiInterni/NormeDiProgetto/Sezioni/Appendice.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/ProcessiOrganizzativi.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Sottosezioni/Supporto/GestioneDellaConfigurazione.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Sottosezioni/Sviluppo/Progettazione.tex
  DocumentiInterni/VerbaliInterni/VI_2021_02_09/Sezioni/Contenuto.tex
  DocumentiPubblici/PianoDiProgetto/Immagini/GanttProgettazioneArchitetturale.png
  DocumentiPubblici/PianoDiProgetto/PianoDiProgetto_v2.0.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/AttualizzazioneDeiRischi.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Comandi.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Consuntivo.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Introduzione.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Organigramma.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Preventivo.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Sottosezioni/AnalisiDeiRischi/Persone.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Sottosezioni/AnalisiDeiRischi/Requisiti.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Sottosezioni/AnalisiDeiRischi/Tecnologie.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Sottosezioni/Consuntivo/ConsuntivoAnalisi.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Sottosezioni/Consuntivo/ConsuntivoProgettazioneArchitetturale.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Sottosezioni/Pianificazione/Analisi.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Sottosezioni/Pianificazione/ProgettazioneArchitetturale.tex
  DocumentiPubblici/PianoDiProgetto/Sezioni/Sottosezioni/Pianificazione/ProgettazioneDiDettaglioECodifica.tex
  DocumentiPubblici/PianoDiQualifica/Immagini/ACWP_PArchitetturale.png
  DocumentiPubblici/PianoDiQualifica/Immagini/BCWP_PArchitetturale.png
  DocumentiPubblici/PianoDiQualifica/Immagini/BCWS_PArchitetturale.png
  DocumentiPubblici/PianoDiQualifica/Immagini/BV_PArchitetturale.png
  DocumentiPubblici/PianoDiQualifica/Immagini/GulpeaseProgettazioneArchitetturale.PNG
  DocumentiPubblici/PianoDiQualifica/Immagini/MPR03_cortografica.png
  DocumentiPubblici/PianoDiQualifica/Immagini/MPR10_rproblemi.png
  DocumentiPubblici/PianoDiQualifica/Immagini/SV_PArchitetturale.png
  DocumentiPubblici/PianoDiQualifica/Sezioni/Comandi.tex
  DocumentiPubblici/PianoDiQualifica/Sezioni/Introduzione.tex
  DocumentiPubblici/PianoDiQualifica/Sezioni/ListaControllo.tex
  DocumentiPubblici/PianoDiQualifica/Sezioni/Miglioramento.tex
  DocumentiPubblici/PianoDiQualifica/Sezioni/QualitaProcesso.tex
  DocumentiPubblici/PianoDiQualifica/Sezioni/QualitaProdotto.tex
  DocumentiPubblici/PianoDiQualifica/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/PianoDiQualifica/Sezioni/Resoconto.tex
  DocumentiPubblici/PianoDiQualifica/Sezioni/SpecificaTest.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_02_04/Sezioni/Contenuto.tex
Labels: bug, documentation, enhancement, help wanted, pdp, pdq, verifica

#235 Feature/aggiunta glo
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/PDP.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/RicercaDeiProdotti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiRicercaDeiProdotti.tex
Labels: adr, documentation

#227 Feature/fix registri
  DocumentiInterni/NormeDiProgetto/NormeDiProgetto_v2.0.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Comandi.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Introduzione.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/ProcessiOrganizzativi.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/ProcessiPrimari.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/RegistroModifiche.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Sottosezioni/Supporto/Documentazione.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Sottosezioni/Supporto/GestioneDellaConfigurazione.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Sottosezioni/Supporto/GestioneDellaQualita.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Sottosezioni/Supporto/Validazione.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Sottosezioni/Sviluppo/AnalisiRequisiti.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Sottosezioni/Sviluppo/CodificaSw.tex
  DocumentiInterni/VerbaliInterni/VI_2021_01_30/Sezioni/Comandi.tex
  DocumentiInterni/VerbaliInterni/VI_2021_01_30/Sezioni/Contenuto.tex
  DocumentiInterni/VerbaliInterni/VI_2021_01_30/Sezioni/RegistroModifiche.tex
  DocumentiInterni/VerbaliInterni/VI_2021_02_09/Sezioni/Comandi.tex
  DocumentiInterni/VerbaliInterni/VI_2021_02_09/Sezioni/Contenuto.tex
  DocumentiInterni/VerbaliInterni/VI_2021_02_09/Sezioni/RegistroModifiche.tex
  DocumentiInterni/VerbaliInterni/VI_2021_02_16/Sezioni/Comandi.tex
  DocumentiInterni/VerbaliInterni/VI_2021_02_16/Sezioni/Contenuto.tex
  DocumentiInterni/VerbaliInterni/VI_2021_02_16/Sezioni/RegistroModifiche.tex
  DocumentiInterni/VerbaliInterni/VI_2021_02_23/Sezioni/Comandi.tex
  DocumentiInterni/VerbaliInterni/VI_2021_02_23/Sezioni/Contenuto.tex
  DocumentiInterni/VerbaliInterni/VI_2021_02_23/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/AccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Comandi.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/TracciamentoDeiRequisiti.tex
  DocumentiPubblici/Glossario/Glossario_v2.0.tex
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/B.tex
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/C.tex
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/D.tex
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/F.tex
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/J.tex
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/M.tex
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/N.tex
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/O.tex
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/Q.tex
  DocumentiPubblici/Glossario/Sezioni/Alfabeto/V.tex
  DocumentiPubblici/Glossario/Sezioni/Comandi.tex
  DocumentiPubblici/Glossario/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/Glossario/Sezioni/SigleAbbreviazioni.tex
  DocumentiPubblici/Lettere/RP/LetteraRP.tex
  DocumentiPubblici/PianoDiQualifica/Sezioni/Comandi.tex
  DocumentiPubblici/PianoDiQualifica/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_02_06/Sezioni/Comandi.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_02_06/Sezioni/Contenuto.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_02_06/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_02/Sezioni/Comandi.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_02/Sezioni/Contenuto.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_02/Sezioni/RegistroModifiche.tex
Labels: verifica

#231 Feature/aggiunta uml riepilogo
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma/AutenticazioneAcquirente.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma/AutenticazioneVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma/InserimentoDatiAutenticazione.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma/InserimentoDatiRegistrazione.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma/PasswordDimenticata.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma/Registrazione.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/AutenticazioneAcquirente.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/AutenticazioneVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/FiltraggioProdotti.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/InserimentoDatiAutenticazione.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/InserimentoDatiRegistrazione.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/PasswordDimenticata.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/Registrazione.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UsoPiattaformaAcquirenteUtenteNonAutenticato.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UsoPiattaformaVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/AccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/RicercaDeiProdotti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Attori.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/RiepilogoUC/RiepilogoUC.tex
Labels: Use Case, adr, documentation

#242 Ultimi check AdR
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Acquirente/Checkout.png
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Comandi.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/DescrizioneDelProdotto.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Introduzione.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti.tex
Labels: adr, documentation

#245 Stesura Verbale 16-03
  DocumentiInterni/NormeDiProgetto/Sezioni/ProcessiPrimari.tex
  DocumentiInterni/NormeDiProgetto/Sezioni/Sottosezioni/Supporto/Documentazione.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Introduzione.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Qualita.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Tracciamento/FonteRequisiti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Tracciamento/RequisitoFonti.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_16/Sezioni/Comandi.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_16/Sezioni/Contenuto.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_16/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/VerbaliEsterni/VE_2021_03_16/VE_2021_03_16.tex
  Utilita/Comandi.tex
  Utilita/Stiletemplate.sty
Labels: verbale, verifica

#257 Feature/correzioni rp
  DocumentiPubblici/AnalisiDeiRequisiti/AnalisiDeiRequisiti_v2.1.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma/AutenticazioneAcquirente.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma/AutenticazionePiattaforma.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/AccessoAllaPiattaforma/AutenticazioneVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UsoPiattaformaAcquirenteUtenteNonAutenticato.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UsoPiattaformaVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/UtenteAutenticato/ModificaPassword.png
  DocumentiPubblici/AnalisiDeiRequisiti/Immagini/DiagrammiUC/Venditore/ModificaPasswordVenditore.png
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/AccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/Checkout/Checkout.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Acquirente/GestioneAccountAcquirente.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/RiepilogoUC/RiepilogoUC.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/CasiUso/Venditore/GestioneAccountVenditore.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Comandi.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/RegistroModifiche.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAccessoAllaPiattaforma.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiCheckout.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiGestioneAccountAcquirente.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiAcquirente/RequisitiPDP.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Requisiti/Funzionali/RequisitiVenditore/RequisitiGestioneAccountVenditore.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Tracciamento/FonteRequisiti.tex
  DocumentiPubblici/AnalisiDeiRequisiti/Sezioni/Tracciamento/RequisitoFonti.tex
Labels: adr, documentation
